.TH "GPGME" "1" "08 July 2012" "gpgme" "User commands"

.SH NAME
gpgme\-config \- script to get information about the installed version of GPGME

.SH SYNOPSIS
.B  gpgme\-config
.RB [ \-\-api\-version ]
.RB [ \-\-cflags ]
.RB [ \-\-exec\-prefix ]
.RB [ \-\-get\-gpg ]
.RB [ \-\-get\-gpgsm ]
.RB [ \-\-host ]
.RB [ \-\-libs ]
.RB [ \-\-prefix ]
.RB [ \-\-thread=pthread ]
.RB [ \-\-version ]

.SH DESCRIPTION
.PP
\fBgpgme\-config\fP is a tool that is used to configure to determine
the compiler and linker flags that should be used to compile
and link programs that use \fIGPGME\fP. It is also used internally
to the .m4 macros for GNU autoconf that are included with \fIGPGME\fP.

.SH OPTIONS
.PP
\fBgpgme\-config\fP accepts the following options:
.TP
.B \-\-api\-version
Print the currently installed API version of \fIGPGME\fP to standard output.
.TP
.B \-\-cflags
Print the compiler flags that are necessary to compile a \fIGPGME\fP program.
.TP
.B \-\-exec\-prefix
Print the exec prefix that was used to configure the \fIGPGME\fP build.
.TP
.B \-\-get\-gpg
Print the path to the
.BR gpg (1)
binary used to configure the \fIGPGME\fP build.
.TP
.B \-\-get\-gpgsm
Print the path to the
.BR gpgsm (1)
binary used to configure the \fIGPGME\fP build.
.TP
.B \-\-host
Print host information.
.TP
.B \-\-libs
Print the linker flags that are necessary to link a \fIGPGME\fP program.
.TP
.B \-\-prefix
Print the prefix that was used to configure the \fIGPGME\fP build.
.TP
.B \-\-thread=pthread
Switch for the
.B \-\-cflags
and
.B \-\-libs
options for the thread-enabled \fIGPGME\fP version.
.TP
.B \-\-version
Print the currently installed version of \fIGPGME\fP to standard output.

.SH AUTHORS
.PP
.PP
The
.I GPGME
library is written by many contributors, including Werner Koch, Marcus
Brinkmann, Andre Heinecke, Justus Winter, and Karl-Heinz Zimmer.
.PP
This manual page page was written by \fBJose Carlos Garcia Sogo\fR
\&<\&jsogo@debian.org\&> and \fBDaniel Leidert\fR <\&daniel.leidert@wgdd.de\&>
for the Debian distribution (but may be used by others).

.SH BUGS
.PP
Please report bugs to <https://bugs.gnupg.org>.

.SH COPYRIGHT
\fBgpgme\-tool\fP is Copyright \(co 2015-2016 g10 Code GmbH License
GPLv2+: GNU GPL version 2 or later <https://www.gnu.org/licenses/>
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH "SEE ALSO"
.BR gpgme\-tool (1),
.BR /usr/include/gpgme.h ,
.B info gpgme
